monolog:
    channels: [transaction]   # Custom channel
    handlers:
        transaction:   # Custom handler
            # level: debug
            type: stream
            path:  "%kernel.logs_dir%/transactions_%kernel.environment%.log"   # Custom log file
            channels: ['transaction']   # Custom channel
            # formatter: app_transaction.formatter.transaction   # Custom formatter

        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
   
        